### ISSUE TITLE
jx create cluster fails at first due to missing project and google account configuration

### ISSUE THREAD

**Issue by vilacides** [jenkins-x/jx-tutorial#38]
Tutotial type: GKE in Google Shell

Traceback:
```
m_vilacides@cloudshell:~/jx-tutorial$ jx create cluster gke --skip-login
Using the only Google Cloud Project Listed to create the cluster
ERROR: (gcloud.config.set) The project property must be set to a valid project ID, not the project name [Listed]
To set your project, run:
  $ gcloud config set project PROJECT_ID
or to unset it, run:
  $ gcloud config unset project
Error: Command failed  gcloud config set project Listed
error creating cluster exit status 1
error: exit status 1
```

**Comment by vilacides** [comment]
Setting the project doesn't work and it fails afterwards, so trying with:
`gcloud projects create vilacides84`
and then `gcloud config set project vilacides84`. 

Then I try again `m_vilacides@vilacides84:~/jx-tutorial$ jx create cluster gke --skip-login` and it seems to work: 

```
Using the only Google Cloud Project vilacides84 to create the cluster
Updated property [core/project].
```

But then it fails again due to not having container and compute enabled in my project:

```
Lets ensure we have container and compute enabled on your project via: gcloud services enable container compute
ERROR: (gcloud.services.enable) FAILED_PRECONDITION: Operation does not satisfy the following requirements: billing-enabled {Billing must
 be enabled for activation of service '' in project 'vilacides84' to proceed., https://console.developers.google.com/project/vilacides84/
settings}
Error: Command failed  gcloud services enable container compute
error creating cluster exit status 1
error: exit status 1
```

**Comment by vilacides** [comment]
I am very obedient so I follow the instructions and now I hit a problem with my google cloud account settings:
```
m_vilacides@vilacides84:~/jx-tutorial$ gcloud services enable container compute
ERROR: (gcloud.services.enable) FAILED_PRECONDITION: Operation does not satisfy the following requirements: billing-enabled {Billing must
 be enabled for activation of service '' in project 'vilacides84' to proceed., https://console.developers.google.com/project/vilacides84/
settings}
```

**Comment by rawlingsj** [comment]
Sorry for the delay!  I think this is because we all had a google cloud account setup already.  We've added a prereqs section to the docs which works with the free tier https://github.com/jenkins-x/jx-tutorial/commit/0fdacd82ee61bce6efbc3b0582f1e89be428768c

Also if you want to ping me internally I can get you added to our google project.

Closing but please reopen if this doesn't help.

**Comment by dennisnewel** [comment]
It should probably be mentioned somewhere (https://jenkins-x.io/getting-started/tutorials/) that you need a gcloud account as well as a project before starting the tutorial. 

Hit the missing project error as well, despite having a gcloud account, but i didn't have a project (and also didn't have permissions to create a project). I switched to another account and got going, but it would have saved some time and confusion (esp. if you're brand new to GCP)
