### ISSUE TITLE
Step 3: Promotion

### ISSUE THREAD

**Issue by pmuir** [jenkins-x/jx-tutorial#39]
I was asked to log in to github for the promotion part of Step 3 (https://github.com/jenkins-x/jx-tutorial/blob/master/tutorials/install-jx-on-gke/lesson.md#promote-the-app-to-production). Because of 2FA my github password didn't work and I needed to use the access token from https://github.com/jenkins-x/jx-tutorial/blob/master/tutorials/install-jx-on-gke/lesson.md#github-connectivity - this should be mentioned in the tutorial.

**Comment by cagiti** [comment]
I stumbled across the same thing, raised here https://github.com/jenkins-x/jx-tutorial/pull/632
