### ISSUE TITLE
create cluster fails with error

### ISSUE THREAD

**Issue by dennisnewel** [jenkins-x/jx-tutorial#509]
## Steps to reproduce
* initiate cloud shell
* follow steps 1 & 2

## Expected outcome
A new cluster created as a result of Step 2

## Actual Outcome
```
dennis_newel@cloudshell:~/jx-tutorial (dnewel-jx-test)$ jx create cluster gke --skip-login
? Google Cloud Project: dnewel-jx-test
Updated property [core/project].
Let's ensure we have container and compute enabled on your project via: gcloud services enable container compute
Operation "operations/acf.f394aa18-08a6-4148-8236-96336d0c11a9" finished successfully.
No cluster name provided so using a generated one: scorpionwool
? Google Cloud Zone: us-central1-a
? Google Cloud Machine Type: n1-standard-2
? Minimum number of Nodes 3
? Maximum number of Nodes 5
? Would you like use preemptible VMs? No
? Would you like to access Google Cloud Storage / Google Container Registry? No
Creating cluster...
Error: Command failed  gcloud container clusters create scorpionwool --zone us-central1-a --num-nodes 3 --machine-type n1-standard-2 --enable-autoscaling --min-nodes 3 --max-nodes 5 --labels=created-by=dennis-newel
error creating cluster exit status 1
```

no other info unfortunately...

**Comment by dennisnewel** [comment]
found a possible cause of the error.

turns out the cluster(s) was actually created, but the project was not connected to a billing account at the time. Looking at the one of the failed clusters, it shows an error of

```
Google Compute Engine: Project dnewel-jx-test cannot accept requests to compute.projects.setCommonInstanceMetadata while in an inactive billing state. Billing state may take several minutes to update.
```

if this sounds like a plausible cause, it might be enough with a documentation update :)

**Comment by TonyApuzzo** [comment]
I have a similar problem -- if you have 2 or more google accounts registered in the browser that is running the tutorial AND you are running the tutorial from the NON default account, then `jx cluster create --skip-login` creates the cluster in the correct account but after that everything falls apart rather quickly and all the team / RBAC / helm related stuff dies.

**Comment by TonyApuzzo** [comment]
I have a similar problem -- if you have 2 or more google accounts registered in the browser that is running the tutorial AND you are running the tutorial from the NON default account, then `jx cluster create --skip-login` creates the cluster in the correct account but after that everything falls apart rather quickly and all the team / RBAC / helm related stuff dies.
