### ISSUE TITLE
GKE questions have changed

### ISSUE THREAD

**Issue by dennisnewel** [jenkins-x/jx-tutorial#511]
There's a discrepancy between the questions asked while setting up a GKE cluster:

```
? Google Cloud Zone: us-central1-a
? Google Cloud Machine Type: n1-standard-2
? Minimum number of Nodes 3
? Maximum number of Nodes 5
? Would you like use preemptible VMs? No
? Would you like to access Google Cloud Storage / Google Container Registry? No
```

and those mentioned in the tutorial
```
Google Compute Zone - select a zone that is near to you
Machine Type - recommended n1-standard-2
Minimum Node Count - recommended 3
Maximum Node Count - recommended 5
Ingress Controller - recommended Yes
Domain Configuration - recommended Use the default
```

applies to https://github.com/jenkins-x/jx-tutorial/blob/master/tutorials/install-jx-on-gke/lesson.md and possibly https://github.com/jenkins-x/jx-tutorial/blob/master/tutorials/install-jx-on-gke-with-terraform/lesson.md as well?

**Comment by dennisnewel** [comment]
not sure what the recommended defaults should be, so i didn't raise a PR :)

**Comment by garethjevans** [comment]
These have been updated
